import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import LoginWithMetamask from './components/LoginWithMetamask';

export default function Home() {
  return (
    <>
      <Head>
        <title>BlockBud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.title}>BlockBud</h1>
        <p className={styles.description}>Connect your wallet to continue</p>
        <LoginWithMetamask />
      </div>
    </>
  );
}
